# Generated by Django 5.2.3 on 2025-09-20 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_document_spacy_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="updated_by",
        ),
    ]
