# Generated by Django 5.2.3 on 2025-11-19 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_case_updated_at_remove_case_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionContext',
            fields=[
                ('redaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='context', serialize=False, to='cases.redaction')),
                ('text', models.TextField(help_text='User-provided context for the redaction.')),
            ],
        ),
    ]
