# Generated by Django 5.2.3 on 2026-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0009_redactioncontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_tables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
