# Generated by Django 5.2.3 on 2026-02-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_document_extracted_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
