# Generated by Django 5.2.3 on 2026-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_document_extracted_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPROCESSED", "Unprocessed"),
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready for Review"),
                    ("COMPLETED", "Completed"),
                    ("ERROR", "Error"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
