# Generated by Django 5.2.3 on 2026-03-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0013_exemption_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentExportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "footer_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "watermark_text",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "watermark_include_case_ref",
                    models.BooleanField(default=False),
                ),
                ("page_numbers_enabled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Document Export Settings",
                "verbose_name_plural": "Document Export Settings",
            },
        ),
    ]
