# Generated by Django 5.2.3 on 2026-03-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0014_documentexportsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentexportsettings",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("arial", "Arial"),
                    ("times_new_roman", "Times New Roman"),
                    ("courier_new", "Courier New"),
                    ("georgia", "Georgia"),
                    ("verdana", "Verdana"),
                ],
                default="arial",
                max_length=50,
            ),
        ),
    ]
