# Generated by Django 5.2.3 on 2026-03-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0015_documentexportsettings_font_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
