# Generated by Django 5.2.12 on 2026-04-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0016_add_case_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="redaction",
            name="source",
            field=models.CharField(
                choices=[("NER", "NER"), ("LLM", "LLM")],
                default="NER",
                help_text="Whether this redaction was produced by an NER model or an LLM.",
                max_length=3,
            ),
        ),
    ]
