# Generated by Django 5.2.12 on 2026-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0017_redaction_source"),
        ("training", "0006_custom_recognizer_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="document_status_idx"),
        ),
        migrations.AddIndex(
            model_name="redaction",
            index=models.Index(
                fields=["text", "redaction_type"],
                name="redaction_text_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="redaction",
            index=models.Index(
                fields=["document", "start_char", "end_char"],
                name="redaction_doc_pos_idx",
            ),
        ),
    ]
