# Generated by Django 5.2.14 on 2026-06-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0018_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewWorkflowSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_accept_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, all NER redaction suggestions are automatically accepted on processing.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Workflow Settings",
                "verbose_name_plural": "Review Workflow Settings",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="redaction",
            name="auto_accepted",
            field=models.BooleanField(
                default=False,
                help_text="True if accepted automatically by the system (not by a human reviewer).",
            ),
        ),
    ]
