# Generated by Django 5.2.14 on 2026-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0019_auto_accept_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentexportsettings",
            name="disclosure_style",
            field=models.CharField(
                choices=[("bars", "Black Bars"), ("removal", "Remove Text")],
                default="bars",
                max_length=20,
            ),
        ),
    ]
