# Generated by Django 5.2.14 on 2026-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0020_documentexportsettings_disclosure_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_reference",
            field=models.CharField(
                help_text="The human-readable, unique identifier for this case, max 6 characters (e.g., 202501).",
                max_length=6,
                unique=True,
            ),
        ),
    ]
