# Generated by Django 5.2.14 on 2026-07-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0021_alter_case_case_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="redaction",
            name="decided_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HUMAN", "Human reviewer"),
                    ("AUTO", "Auto-accept review mode"),
                    ("CASE_PROP", "Unanimous case-decision propagation"),
                    ("DS_PROP", "DS information propagation"),
                ],
                help_text="Who/what made the accept/reject decision. NULL = pending.",
                max_length=9,
                null=True,
            ),
        ),
    ]
