# Generated by Django 5.2.14 on 2026-07-07 23:25

from django.db import migrations
from django.db.models import Q


def backfill_decided_by(apps, schema_editor):
    """
    Derive provenance for existing decisions from the auto_accepted flag.

    Pre-migration case-propagated accepts are indistinguishable from human
    accepts and are deliberately backfilled as HUMAN: excluding all legacy
    decisions from training would gut the existing corpus, which SpanCat
    cannot afford given its sensitivity to class imbalance.
    """
    Redaction = apps.get_model("cases", "Redaction")

    Redaction.objects.filter(is_accepted=True, auto_accepted=True).update(
        decided_by="AUTO"
    )
    Redaction.objects.filter(is_accepted=True, auto_accepted=False).update(
        decided_by="HUMAN"
    )
    # Explicit rejections (non-blank justification); everything else stays
    # NULL = pending.
    Redaction.objects.filter(is_accepted=False).exclude(
        Q(justification__isnull=True) | Q(justification="")
    ).update(decided_by="HUMAN")


def restore_auto_accepted(apps, schema_editor):
    Redaction = apps.get_model("cases", "Redaction")
    Redaction.objects.filter(is_accepted=True, decided_by="AUTO").update(
        auto_accepted=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0022_redaction_decided_by"),
    ]

    operations = [
        migrations.RunPython(backfill_decided_by, restore_auto_accepted),
    ]
