# Generated by Django 5.2.14 on 2026-07-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0023_backfill_decided_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redaction",
            name="auto_accepted",
        ),
        migrations.AddConstraint(
            model_name="redaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_accepted", False),
                    ("decided_by__isnull", False),
                    _connector="OR",
                ),
                name="redaction_accept_requires_decided_by",
            ),
        ),
    ]
