# Generated by Django 5.2.14 on 2026-07-15 19:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0024_remove_redaction_auto_accepted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedactionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.JSONField(
                        default=list,
                        editable=False,
                        help_text="Frozen list of every redaction (all fields) plus associated RedactionContext for the case's documents at capture time.",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redaction_snapshots",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
