# Generated by Django 5.2.14 on 2026-07-15 22:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cases.models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0025_redactionsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_file",
                    models.FileField(
                        help_text="The preserved ZIP package for this disclosure.",
                        upload_to=cases.models.export_upload_to,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="1-based order of this export within the case."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Human label, e.g. "Original disclosure" or "Disclosure 2".',
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddField(
            model_name="redactionsnapshot",
            name="export",
            field=models.OneToOneField(
                blank=True,
                help_text="The export this snapshot froze the redaction set for.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshot",
                to="cases.export",
            ),
        ),
        migrations.CreateModel(
            name="InternalReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required written outcome recorded when the review is closed.",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cases.case",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="export",
            name="review",
            field=models.ForeignKey(
                blank=True,
                help_text="The review that produced this export; null for the original disclosure.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exports",
                to="cases.internalreview",
            ),
        ),
        migrations.AddConstraint(
            model_name="export",
            constraint=models.UniqueConstraint(
                fields=("case", "sequence"), name="export_unique_case_sequence"
            ),
        ),
    ]
