# Generated by Django 5.2.14 on 2026-07-15 22:50

from django.db import migrations

# Kept in sync with cases.snapshots._SNAPSHOT_FIELDS. Duplicated here rather
# than imported because data migrations must bind to historical models.
_SNAPSHOT_FIELDS = (
    "id",
    "document_id",
    "start_char",
    "end_char",
    "text",
    "justification",
    "redaction_type",
    "is_suggestion",
    "is_accepted",
    "decided_by",
    "source",
)


def backfill_exports(apps, schema_editor):
    """
    Wrap each legacy Case.export_file in a first-class Export row plus a
    best-effort baseline RedactionSnapshot built from the case's current live
    redactions.

    Assumes no drift since disclosure: the live redaction set is treated as
    the as-disclosed record. Legacy cases thereby become reviewable with an
    honest, approximate baseline.
    """
    Case = apps.get_model("cases", "Case")
    Redaction = apps.get_model("cases", "Redaction")
    RedactionContext = apps.get_model("cases", "RedactionContext")
    Export = apps.get_model("cases", "Export")
    RedactionSnapshot = apps.get_model("cases", "RedactionSnapshot")

    legacy_cases = Case.objects.exclude(export_file="").exclude(
        export_file__isnull=True
    )
    for case in legacy_cases.iterator():
        if case.exports.exists():
            continue

        export = Export.objects.create(
            case=case,
            export_file=case.export_file.name,
            sequence=1,
            label="Original disclosure",
            created_by=None,
            review=None,
        )

        redactions = Redaction.objects.filter(document__case=case).order_by(
            "created_at", "id"
        )
        context_by_redaction = {
            rc.redaction_id: rc.text
            for rc in RedactionContext.objects.filter(
                redaction__document__case=case
            )
        }

        payload = []
        for redaction in redactions:
            row = {
                field: getattr(redaction, field) for field in _SNAPSHOT_FIELDS
            }
            row["id"] = str(redaction.id)
            row["document_id"] = str(redaction.document_id)
            row["created_at"] = redaction.created_at.isoformat()
            row["context"] = context_by_redaction.get(redaction.id)
            payload.append(row)

        RedactionSnapshot.objects.create(
            case=case, export=export, payload=payload
        )


def unbackfill_exports(apps, schema_editor):
    """Remove the sequence-1 "Original disclosure" exports this migration made."""
    Export = apps.get_model("cases", "Export")
    Export.objects.filter(
        sequence=1, label="Original disclosure", review__isnull=True
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "cases",
            "0026_export_redactionsnapshot_export_internalreview_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(backfill_exports, unbackfill_exports),
    ]
