# Generated by Django 5.2.12 on 2026-04-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_create_api_service_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Key expires at this time. Leave blank for no expiry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this key was used to authenticate.",
                null=True,
            ),
        ),
    ]
