from django.urls import path

from .views import (
    BulkByTextRedactionView,
    BulkCaseDeleteView,
    BulkRedactionUpdateView,
    CaseDetailView,
    CaseDisclosureDiffView,
    CaseExportHistoryView,
    CaseExportView,
    CaseListCreateView,
    CaseReviewCloseView,
    CaseReviewView,
    DocumentCancelProcessingView,
    DocumentDetailView,
    DocumentExportSettingsView,
    DocumentListCreateView,
    DocumentResubmitView,
    DocumentReviewView,
    ExemptionTemplateDetailView,
    ExemptionTemplateListView,
    RedactionContextView,
    RedactionDetailView,
    RedactionListCreateView,
    RedactionPropagationView,
    RetentionSettingsView,
    ReviewWorkflowSettingsView,
)

urlpatterns = [
    path(
        "cases/settings/export",
        DocumentExportSettingsView.as_view(),
        name="export-settings",
    ),
    path(
        "cases/settings/retention",
        RetentionSettingsView.as_view(),
        name="retention-settings",
    ),
    path(
        "cases/settings/review-workflow",
        ReviewWorkflowSettingsView.as_view(),
        name="review-workflow-settings",
    ),
    path(
        "cases/settings/retention/bulk-delete",
        BulkCaseDeleteView.as_view(),
        name="bulk-case-delete",
    ),
    path(
        "cases/exemptions",
        ExemptionTemplateListView.as_view(),
        name="exemption-template-list",
    ),
    path(
        "cases/exemptions/<int:pk>",
        ExemptionTemplateDetailView.as_view(),
        name="exemption-template-detail",
    ),
    path("cases", CaseListCreateView.as_view(), name="case-list-create"),
    path("cases/<uuid:case_id>", CaseDetailView.as_view(), name="case-detail"),
    path(
        "cases/<uuid:case_id>/export",
        CaseExportView.as_view(),
        name="case-export",
    ),
    path(
        "cases/<uuid:case_id>/exports",
        CaseExportHistoryView.as_view(),
        name="case-exports",
    ),
    path(
        "cases/<uuid:case_id>/diff",
        CaseDisclosureDiffView.as_view(),
        name="case-diff",
    ),
    path(
        "cases/<uuid:case_id>/reviews",
        CaseReviewView.as_view(),
        name="case-review-open",
    ),
    path(
        "cases/<uuid:case_id>/reviews/complete",
        CaseReviewCloseView.as_view(),
        {"action": "complete"},
        name="case-review-complete",
    ),
    path(
        "cases/<uuid:case_id>/reviews/abandon",
        CaseReviewCloseView.as_view(),
        {"action": "abandon"},
        name="case-review-abandon",
    ),
    path(
        "cases/<uuid:case_id>/documents",
        DocumentListCreateView.as_view(),
        name="document-list-create",
    ),
    path(
        "cases/documents/<uuid:document_id>",
        DocumentDetailView.as_view(),
        name="document-detail",
    ),
    path(
        "cases/documents/<uuid:document_id>/resubmit",
        DocumentResubmitView.as_view(),
        name="document-resubmit",
    ),
    path(
        "cases/documents/<uuid:document_id>/cancel",
        DocumentCancelProcessingView.as_view(),
        name="document-cancel",
    ),
    path(
        "cases/<uuid:case_id>/document/<uuid:document_id>/review",
        DocumentReviewView.as_view(),
        name="document-review",
    ),
    path(
        "cases/document/<uuid:document_id>/redaction",
        RedactionListCreateView.as_view(),
        name="redaction-list-create",
    ),
    path(
        "cases/document/redaction/<uuid:pk>",
        RedactionDetailView.as_view(),
        name="redaction-detail",
    ),
    path(
        "cases/document/<uuid:document_id>/redactions/bulk/",
        BulkRedactionUpdateView.as_view(),
        name="bulk-redaction-update",
    ),
    path(
        "cases/<uuid:case_id>/redactions/bulk-by-text/",
        BulkByTextRedactionView.as_view(),
        name="bulk-by-text-redaction-update",
    ),
    path(
        "cases/document/redaction/<uuid:redaction_id>/context",
        RedactionContextView.as_view(),
        name="redaction-context",
    ),
    path(
        "cases/document/redaction/<uuid:redaction_id>/propagation",
        RedactionPropagationView.as_view(),
        name="redaction-propagation",
    ),
]
