# Generated by Django 5.2.3 on 2025-08-28 22:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A unique name for the model version (e.g., v2.1-timestamp).', max_length=255, unique=True)),
                ('path', models.CharField(help_text='The absolute file path to the trained model directory.', max_length=512, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Designates if this model is the one currently used for processing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
