# Generated by Django 5.2.12 on 2026-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "training",
            "0003_trainingdocument_trainingentity_trainingrun_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMPromptSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a data protection specialist reviewing documents for Subject\nAccess Requests (SARs) under UK GDPR and the Data Protection Act 2018.\n\nYour task: identify text that must be redacted to protect third parties, while allowing\nthe data subject's own information to be disclosed.\n\nRules:\n- Redact names, addresses, and identifying details of people who are NOT the data subject\n- Redact operational information that would identify third-party officers or staff\n- Do NOT redact information that is solely about the data subject\n- Return only text that appears verbatim in the document"
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Prompt Settings",
                "verbose_name_plural": "LLM Prompt Settings",
            },
        ),
    ]
