# Generated by Django 5.2.3 on 2025-09-14 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_document_spacy_model'),
        ('training', '0003_auto_20250911_2032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='training_docs/')),
                ('extracted_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
                ('label', models.CharField(choices=[('DS_INFORMATION', 'Data Subject Information'), ('THIRD_PARTY', 'Third Party Information'), ('OPERATIONAL', 'Operational Information')], max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='training.trainingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('training_docs', 'Training Documents'), ('redactions', 'Redactions'), ('both', 'Both')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.model')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRunCaseDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.document')),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingrun')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRunTrainingDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingdocument')),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingrun')),
            ],
        ),
    ]
