# Generated by Django 5.2.12 on 2026-04-18 22:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0005_alter_llmpromptsettings_system_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRecognizer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("THIRD_PARTY", "Third-Party PII"),
                            ("OPERATIONAL", "Operational Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("regex", models.TextField()),
                ("score", models.FloatField(default=0.85)),
                (
                    "recognizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patterns",
                        to="training.customrecognizer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomDenyListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "recognizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deny_list",
                        to="training.customrecognizer",
                    ),
                ),
            ],
        ),
    ]
